### ISSUE TITLE
Prevent from downloads without code

### ISSUE THREAD

**Issue by DevStarlight** [Videona/platform-frontend#22]
Obfuscate the download URL to make as difficult as possible to get the video without code.

**Comment by CodingCarlos** [comment]
Why is this a bug?

**Comment by DevStarlight** [comment]
After talking with @CodingCarlos about the potential problem exposing the full URL, it's concluded that it's possible to download the sample video. About the problem of massive downloads, the firewall is working here preventing attacks.
